(deftheme chrislol
  "Created 2018-10-10.")

(custom-theme-set-faces
 'chrislol
 '(default ((t (:inherit nil :stipple nil :background "magenta" :foreground "#ffffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :foundry "SRC" :family "Hack"))))
 '(cursor ((t (:background "#ff9800"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#4dd0e1"))))
 '(highlight ((t (:inverse-video nil :background "#37474f"))))
 '(region ((t (:background "#555555"))))
 '(shadow ((t (:foreground "#b0bec5"))))
 '(secondary-selection ((t (:background "#bf616a"))))
 '(trailing-whitespace ((t (:underline nil :inverse-video t :foreground "#f36c60"))))
 '(font-lock-builtin-face ((t (:foreground "#ff8A65"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#b0bec5"))))
 '(font-lock-comment-face ((t (:foreground "#b0bec5"))))
 '(font-lock-constant-face ((t (:foreground "#8bc34a"))))
 '(font-lock-doc-face ((t (:foreground "moccasin"))))
 '(font-lock-function-name-face ((t (:foreground "#84ffff"))))
 '(font-lock-keyword-face ((t (:foreground "#fff59d"))))
 '(font-lock-negation-char-face ((t (:foreground "#4dd0e1"))))
 '(font-lock-preprocessor-face ((t (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#fff59d"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#b39ddb"))))
 '(font-lock-string-face ((t (:foreground "#9ccc65"))))
 '(font-lock-type-face ((t (:foreground "#84ffff"))))
 '(font-lock-variable-name-face ((t (:foreground "#ffcc80"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#f36c60"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#263238"))))
 '(header-line ((t (:foreground "#b39ddb" :inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#ffffff" :background "#1c1f26"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#ffffff"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#ffffff"))))
 '(mode-line-highlight ((t (:box nil :foreground "#b39ddb"))))
 '(mode-line-inactive ((t (:weight normal :box nil :foreground "#a7adba" :background "#1c1f26" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#ffffff" :background "#8bc34a"))))
 '(isearch-fail ((t (:inverse-video t :background "#263238" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:inverse-video nil :foreground "#263238" :background "#8bc34a"))))
 '(match ((t (:inverse-video nil :foreground "#263238" :background "#8bc34a"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'chrislol)
